name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: subodule init
      run: git submodule init
    - name: subodule update
      run: git submodule update
    - name: configure
      run: cmake ./
    - name: make
      run: cmake --build ./
