name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: subodule init
      run: git submodule init
    - name: subodule update
      run: git submodule update
    - name: Get boost
      run: wget https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.bz2
    - name: Build boost
      run: tar -C ./ -jxf boost_1_70_0.tar.bz2 && cd boost_1_70_0/ && ./bootstrap.sh --prefix=/usr && ./b2 stage threading=multi link=static --with-date_time --with-filesystem --with-system --with-regex
    - name: Install boost
      run: cd boost_1_70_0/ && sudo ./b2 install threading=multi link=static --with-date_time --with-filesystem --with-system --with-regex
    - name: configure
      run: cmake ./
    - name: make
      run: cmake --build ./
